spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:testycool}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_USER_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${SERVER_PORT:50051}

jwt:
  expiration: ${JWT_EXPIRATION:300000}
